name: 'Get Latest Release Branch'
description: 'Checks GitHub release/ branches and returns the latest'
inputs:
  gh_token:
    description: 'GitHub Token'
    required: true

outputs:
  latestRelease:
    description: 'Latest release branch name'  # Updated description to be more accurate
    value: ${{ steps.get_latest_release.outputs.latestRelease }}

runs:
  using: 'composite'
  steps:
    - name: 'Get Latest Release Branch'
      id: get_latest_release
      shell: pwsh
      run: |
        try { 
          & "${{ github.action_path }}/Get-LatestReleaseBranch.ps1" -GH_TOKEN "${{ inputs.gh_token }}" -REPO "${{ github.repository }}" 
        } 
        catch { 
          Write-Host "::error::Unexpected error when running action: $($_.Exception.Message)"
          exit 1 
        }
